name: mega-system
services:
  db:
    image: "postgres:latest"
    volumes:
      - ./.megadb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: asylium
    ports:
      - "5432:5432"
  main:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./project:/home/developer/project
    depends_on:
      - db
